### ISSUE TITLE
Where are the tests?

### ISSUE THREAD

**Issue by brazenbraden** [necolt/Swifton#11]
Not much more I can add to that in here.

**Comment by sauliusgrigaitis** [comment]
@brazenbraden I use Linux and there were no convenient way to run tests on Linux when I started to work on Swifton. I'll try to write test suite ASAP. Meanwhile you can use [TodoApp](https://github.com/necolt/Swifton-TodoApp) for regression testing.

**Comment by sauliusgrigaitis** [comment]
@brazenbraden I added small test suite which should be good enough starting point. Feel free to contribute ;)
