### ISSUE TITLE
Unused variable in ControllerSpec

### ISSUE THREAD

**Issue by j-em** [necolt/Swifton#18]
Hello,

I'm learning Swift and I tried compiling this project for fun and I noticed a compiler warning: `/home/bob/Swifton/Sources/Spec/ControllerSpec.swift:12:17: warning: variable 'record' was written to, but never read
            var record:TestModel!
`

Does holding the result of `TestModel.create()` into `record` have any purposes ?

**Comment by sauliusgrigaitis** [comment]
@j-allard thanks, fixed.
