### ISSUE TITLE
Reliance on Foundation in MimeType.swift

### ISSUE THREAD

**Issue by califrench** [necolt/Swifton#23]
Is it normal that we are importing Foundation in MimeType.swift? This should be a platform agnostic framework and I'm not even sure why we need Foundation in that source file.

**Comment by sauliusgrigaitis** [comment]
@califrench Swifton uses features of [Foundation](https://github.com/apple/swift-corelibs-foundation), so it's platform agnostic framework. But I cleaned `MimeType.swift`, because that [Foundation](https://github.com/apple/swift-corelibs-foundation) isn't actually used in Swifton
