### ISSUE TITLE
Build with error:error: NoSources("xxxxxxx/Packages/PathKit-0.6.1/Tests/Fixtures")

### ISSUE THREAD

**Issue by ipconfiger** [necolt/Swifton#29]
Seem's like there's no suck dictionary or files, bug:

`vagrant@vagrant-ubuntu-wily-64:~/test_proj1/Packages/PathKit-0.6.1/Tests$ ll
total 36
drwxrwxr-x 3 vagrant vagrant  4096 Mar 14 13:36 ./
drwxrwxr-x 8 vagrant vagrant  4096 Mar 14 13:36 ../
drwxrwxr-x 5 vagrant vagrant  4096 Mar 14 13:36 Fixtures/
-rw-rw-r-- 1 vagrant vagrant   733 Mar 14 13:36 Info.plist
-rw-rw-r-- 1 vagrant vagrant  2293 Mar 14 13:36 ManipulationTests.swift
-rw-rw-r-- 1 vagrant vagrant 12605 Mar 14 13:36 PathKitTests.swift
vagrant@vagrant-ubuntu-wily-64:~/test_proj1/Packages/PathKit-0.6.1/Tests$
vagrant@vagrant-ubuntu-wily-64:~/test_proj1/Packages/PathKit-0.6.1/Tests$
vagrant@vagrant-ubuntu-wily-64:~/test_proj1/Packages/PathKit-0.6.1/Tests$
vagrant@vagrant-ubuntu-wily-64:~/test_proj1/Packages/PathKit-0.6.1/Tests$ cd Fixtures/
vagrant@vagrant-ubuntu-wily-64:~/test_proj1/Packages/PathKit-0.6.1/Tests/Fixtures$ ll
total 20
drwxrwxr-x 5 vagrant vagrant 4096 Mar 14 13:36 ./
drwxrwxr-x 3 vagrant vagrant 4096 Mar 14 13:36 ../
drwxrwxr-x 3 vagrant vagrant 4096 Mar 14 13:36 directory/
-rw-rw-r-- 1 vagrant vagrant    0 Mar 14 13:36 file
drwxrwxr-x 2 vagrant vagrant 4096 Mar 14 13:36 permissions/
drwxrwxr-x 2 vagrant vagrant 4096 Mar 14 13:36 symlinks/
vagrant@vagrant-ubuntu-wily-64:~/test_proj1/Packages/PathKit-0.6.1/Tests/Fixtures$`

**Comment by sauliusgrigaitis** [comment]
@ipconfiger thanks, are you using [this](https://github.com/necolt/Swifton/blob/master/.swift-version) Swift version?

**Comment by sauliusgrigaitis** [comment]
@ipconfiger ?

**Comment by sauliusgrigaitis** [comment]
@ipconfiger please reopen if it doesn't work with correct Swift version.
