### ISSUE TITLE
License

### ISSUE THREAD

**Issue by damian-kolakowski** [necolt/Swifton#6]
Hi guys,

I see you are using some code I wrote for my project - https://github.com/glock45/swifter/blob/master/Sources/String%2BMisc.swift

Swifton: https://github.com/necolt/Swifton/blob/master/Sources/Extensions.swift

Can you please add my license to Extensions.swift file ? 

Best and good luck with the project,
DK

**Comment by sauliusgrigaitis** [comment]
Hi @glock45 , thanks for opening this issue, I copied entire file with license, so should be no probs.

**Comment by damian-kolakowski** [comment]
:+1:
