### ISSUE TITLE
UTF8 issue

### ISSUE THREAD

**Issue by sauliusgrigaitis** [necolt/Swifton#9]
Somewhere in the chain encoding is messed up - if I enter issue name "ąęčįčęėįčęėįčęš" in TodoApp I actually get "ÄÄÄÄ¯ÄÄÄÄ¯ÄÄÄÄ¯ÄÄÅ¡   "

**Comment by cobalamin** [comment]
There's two issues here:
- The `Controller` base class doesn't set the charset to utf8 in the contentType parameter.
- But more importantly, the `String` extension method `removePercentEncoding` just messes up everything. Doesn't seem like it's a sensible or correct implementation. I don't know how to properly implement it myself, but I tried, for testing purposes, to use the `NSString` method `stringByReplacingPercentEscapesUsingEncoding` from the Foundation API:

``` swift
public func removePercentEncoding() -> String {
      return self.stringByReplacingPercentEscapesUsingEncoding(NSUTF8StringEncoding)!
}
```

(I'm aware that this should be platform-agnostic and so, using Foundation APIs isn't sensible in actual code here)

Doing both these things seem to solve all these issues for me. So if you get a correct implementation of `removePercentEncoding` and add the encoding to the Content-Type, it should be all good.

**Comment by sauliusgrigaitis** [comment]
@cobalamin thanks a lot, definitely need crossplatform solution, so issue is open.

**Comment by sauliusgrigaitis** [comment]
Was fixed in recent massive upgrade.
